# Generated by Django 5.2.4 on 2025-08-03 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
