# Generated by Django 5.2.4 on 2025-08-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_vehicle_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='From',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='To',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
