# Generated by Django 5.2.4 on 2025-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_vehicle_from_vehicle_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
