# Generated by Django 5.2.4 on 2025-08-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_seat_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='From',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='To',
            new_name='to_location',
        ),
    ]
