# Generated by Django 5.2.4 on 2025-08-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
